# -*- coding: utf-8 -*-
"""facelink

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L_GtqlNqf9i1gaE6WhgHPzH489gTcijM
"""
import sys
import os
import aiohttp
import asyncio
import uvicorn
import numpy as np 
import PIL 
from io import BytesIO
from starlette.applications import Starlette
from starlette.middleware.cors import CORSMiddleware
from starlette.responses import HTMLResponse, JSONResponse
from starlette.staticfiles import StaticFiles
from keras.models import load_model

export_file_url = 'https://www.dropbox.com/s/mcth2eag33g9xdu/Facelink_prototype1.hdf5?dl=0'
export_file_name = 'Facelink_prototype1.hdf5'

classes = ['Rapepong','Preecha']
path = Path(__file__).parent

app = Starlette()
app.add_middleware(CORSMiddleware, allow_origins=['*'], allow_headers=['X-Requested-With', 'Content-Type'])
app.mount('/WebComponent', StaticFiles(directory='app/WebComponent'))


async def download_file(url, dest):
    if dest.exists(): return
    async with aiohttp.ClientSession() as session:
        async with session.get(url) as response:
            data = await response.read()
            with open(dest, 'wb') as f:
                f.write(data)


async def setup_learner():
    await download_file(export_file_url, path / export_file_name)
    try:
        learn = load_model(path/export_file_name)
        return learn
    except RuntimeError as e:
        if len(e.args) > 0 and 'CPU-only machine' in e.args[0]:
            print(e)
            message = "\n\nThis model was trained with an old version of fastai and will not work in a CPU environment.\n\nPlease update the fastai library in your training environment and export your model again.\n\nSee instructions for 'Returning to work' at https://course.fast.ai."
            raise RuntimeError(message)
        else:
            raise


loop = asyncio.get_event_loop()
tasks = [asyncio.ensure_future(setup_learner())]
learn = loop.run_until_complete(asyncio.gather(*tasks))[0]
loop.close()


@app.route('/')
async def homepage(request):
    html_file = path / 'WebComponent' / 'index.html'
    return HTMLResponse(html_file.open().read())

@app.route('/analyze', methods=['POST'])
async def analyze(request):
    img_data = await request.form()
    img_bytes = await (img_data['file'].read())
    img_bytes = np.asarray(img_bytes)
    img = PIL.Image.fromarray(img_bytes)
    image = img.resize((160,160))
    array = np.asarray([image])
    prediction = learn.predict(array)
    decoder ={0:'Rapepong',1:'Preecha'}
    result = np.argmax(prediction)
    return JSONResponse({'result': decoder[result]})


if __name__ == '__main__':
    if 'serve' in sys.argv:
        uvicorn.run(app=app, host='0.0.0.0', port=5000, log_level="info")